@startuml
'TP School UML

:Admin: as Admin
:Enseignant: as Teacher
:Élève: as SchoolStudent

package system{
left to right direction

'********* Admin *********
(Gérer les enseignants) as (ManageTeacher)
(Gérer les élèves) as (ManageSchoolStudent)
(Planifier les cours) as (PlanningLessons)
(Attribuer un enseignant) as (AssignTeacher)

Admin --> ManageTeacher
Admin --> ManageSchoolStudent
Admin --> PlanningLessons
(PlanningLessons) ..> (AssignTeacher) : <<include>>

'********* Teacher *********
(Gérer un cours) as (ManageCourse)
(Consulter la liste des cours) as (ViewCourses)


Teacher --> (ManageCourse)
Teacher --> (ViewCourses)

'********* SchoolStudent *********
(Participer à une classe) as (ParticipateClass)
(S'inscrire à l'école) as (RegisterAtSchool)

SchoolStudent --> (ViewCourses)
SchoolStudent --> (ParticipateClass)
SchoolStudent --> (RegisterAtSchool)
}

@enduml