@startuml
'https://plantuml.com/sequence-diagram

autonumber

!pragma teoz true
!pragma sequenceMessageSpan true

== Participer à un cours ==

Eleve -> System: Consulter la liste des cours
Enseignant -> System: Consulter la liste des cours
alt Eleve et Enseignant existent
    System -> Eleve: Renvoie la liste de cours ou il figure
    System -> Enseignant: Renvoie la liste de cours qu'il doit présenter
else Eleve ou Enseignant non existant
    System -> Eleve: Renvoie une erreur
    System -> Enseignant: Renvoie une erreur
end

System -> Eleve : Terminer le cours
System -> Enseignant : Terminer le cours
alt Fin de la journée
    System -> Enseignant : Message de fin de la journée
    System -> Eleve : Message de fin de la journée
else Fin du cours actuel
    Eleve <- System : Affiche le prochain cours
    Enseignant <- System : Affiche le prochain cours

@enduml
