@startuml
'https://plantuml.com/sequence-diagram

autonumber

!pragma teoz true
!pragma sequenceMessageSpan true

== Attribuer un enseignant à un cours ==

Admin -> System: Renseigne le cours et l'enseignant à une date

alt#Gold #Pink Saisie incorrecte
    System -> Admin : Renvoie une erreur et demande de corriger
end

alt#Gold #LightBlue Enseignant disponible
    System -> Admin: Valide l'assignation et renvoie une confirmation
else #Pink Enseignant indisponible
    System -> Admin: Renvoie une erreur et donne la possibilité de recommencer
end



@enduml
