import abc
from typing import ClassVar
from abc import ABC, abstractmethod
from dataclasses import dataclass
import uuid


@dataclass
class Person(ABC):
    """ An abstract class representing a real person.

     The Person abstract class will create a Person

     Attributes:
         user_id: autogenerated user uuid
         first_name
         last_name
         age
         adress: an Adress Object with a City inside it
         planning: a Planning object with a list of `Date` in it

     """
    ## class attributes `person` that stores everyone
    persons: ClassVar[list['Person']]

    def __init__(self, first_name: str, last_name: str, age: int, adress: Adress ):  # type: ignore
        """ Inits Person with provided data """
        self.first_name: str = first_name
        self.last_name: str = last_name
        self.age: int = age
        self.adress: Adress = adress  # type: ignore
        self.planning: list['Subject'] = []  # type: ignore
        self.user_id: uuid.UUID = uuid.uuid4()


    def __post_init__(self):
        """ Add Person to `persons` list """
        Person.persons.append(self)

    @abc.abstractmethod
    def participate(self) -> None:
        """ This method will be implemented in Child classes """
        pass